Docker, Static Serve, api on /api in new and old backend
faktorzehn/evendemy pull request #28
Opened 2023-08-07 12:48 UTC by if-loop69420

## Changes
- Added a [Dockerfile](https://github.com/if-loop69420/evendemy/blob/UiRenderInDocker/backend/Dockerfile) to the backend folder
- Added a [docker-compose.yml](https://github.com/if-loop69420/evendemy/blob/UiRenderInDocker/docker-compose.yml) to the root folder
- Changed [transoloco root module](https://github.com/if-loop69420/evendemy/blob/UiRenderInDocker/webapp/src/app/transloco-root.module.ts) to allow the frontend to be rendered statically through NextJS
- Added ServeStatic Module to [app.module.ts](https://github.com/if-loop69420/evendemy/blob/UiRenderInDocker/backend/src/app.module.ts)
- Changed the old backend in /server to also use /api as prefix to all endpoints.
- New backend uses /api for all api related routes
- enabled cors on localhost:*
- webapp config now has backend_url as localhost:8080/api

## How to test before merging
- [ ] Have a postgres db running. Doesnt matter if it's in docker or baremetal
- [ ] run the following in bash
```sh
cd <project folder>
docker-compose build
docker-compose up
```
- [ ] open a browser and navigate to http://localhost:8080 and enter admin as the username
- [ ] See rendered frontend hopefully 😄 

## Kind Regards, Jeremy Sztavinovszki

2023-08-10 19:36 UTC, thomaswruss requested changes

2023-08-10 19:36 UTC, thomaswruss commented on backend/src/app.module.ts
> +      rootPath: join(__dirname,"../../../webapp", "dist"),
we only need the dist folder in the docker image

2023-08-10 19:36 UTC, thomaswruss commented on backend/src/main.ts
> +  app.enableCors();
should be only activated in dev mode

2023-08-10 19:36 UTC, thomaswruss commented on docker-compose.yml
> +      - ./backend/:/usr/src/backend/
we only need the dist folder of the webapp and backend

2023-08-10 19:36 UTC, thomaswruss commented on backend/Dockerfile
> +CMD "bash" "-c" "cd /usr/src/backend/ && npm run start"
npm run start will call nest js....in production we should not do that. we can just execute the already compiled main.js file

2023-08-10 19:36 UTC, thomaswruss commented on .env
> +MEETING_IMAGE_PATH=./webapp/src/assets/meeting_images
since we have the images now with a separate request, it is not necessary that the images will be in the assets folder

2023-08-10 19:36 UTC, thomaswruss commented on webapp/src/app/core/http-interceptor/api_interceptor.ts
> +    req.headers
should be activated only in dev mode

2023-08-10 19:36 UTC, thomaswruss commented on webapp/src/app/services/authentication.service.ts
> +      'Access-Control-Allow-Origin': 'http://localhost:8080'
only in dev mode

2023-08-18 07:07 UTC, if-loop69420 commented
Have changed all requested files. Please re-review and merge. I have a branch with github actions on it for this repo, that depends on this and needs to be merged after this has been merged.

2023-08-27 10:40 UTC, merged